[workspace]
members = [
    "programs/*"
]

[workspace.dependencies.wormhole-cctp-program]
package = "wormhole-cctp-solana"
version = "0.0.0-alpha.12"
features = ["cpi"]
default-features = false

[workspace.dependencies.anchor-lang]
version = "0.28.0"
features = ["derive", "init-if-needed"]

[workspace.dependencies]
anchor-spl = "0.28.0"
solana-program = "1.16.16"
hex = "0.4.3"
ruint = "1.9.0"
cfg-if = "1.0"
hex-literal = "0.4.1"

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
