[workspace]
members = [
    "programs/*"
]
resolver = "2"

[workspace.dependencies.wormhole-cctp-solana]
version = "0.0.1-alpha.1"
default-features = false

[workspace.dependencies.anchor-lang]
version = "0.28.0"
features = ["derive", "init-if-needed"]

[workspace.dependencies]
wormhole-io = "0.1.1"
anchor-spl = "0.28.0"
solana-program = "1.16.16"
hex = "0.4.3"
ruint = "1.9.0"
cfg-if = "1.0"
hex-literal = "0.4.1"

### https://github.com/coral-xyz/anchor/issues/2755
### This dependency must be added for each program.
ahash = "=0.8.6"

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
